name       : slop 
version    : 5.3.37
release    : 1
source     :
    - https://github.com/naelstrof/slop/archive/v5.3.37.tar.gz : 3a1656f8ccc53ab5a2c6ffe095893b05cf50a3ba5d33857ecf48ce3f448051dc
license    : GPL-3.0
component  : desktop
summary    : slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
description: |
    slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
libsplit   : no
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(glu)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
