name       : slop
version    : 7.3.49
release    : 4
source     :
    - https://github.com/naelstrof/slop/archive/v7.3.49.tar.gz : 15befb4a2bf2cf15a64d8256ce2d4d6778df9814da9ce3946c7484b8c909b13f
license    : GPL-3.0
component  : desktop
summary    : slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
description: |
    slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
libsplit   : no
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(icu-uc)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
