name       : slop
version    : '7.5'
release    : 13
source     :
    - https://github.com/naelstrof/slop/archive/v7.5.tar.gz : 94d8b6270217cd7f56ce7d4a9a75069025262830a2f91c3239b7fc07da5ea8da
homepage   : https://github.com/naelstrof/slop
license    : GPL-3.0-or-later
component  : desktop
summary    : slop (Select Operation) is an application that queries for a selection
    from the user and prints the region to stdout
description: |
    slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
libsplit   : no
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(icu-uc)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
