name       : slop
version    : 7.4
release    : 8
source     :
    - https://github.com/naelstrof/slop/archive/v7.4.tar.gz : 8868590b0ebb712f82295266cb120f5bda022393d72caafa7564c9fb66ccedce
license    : GPL-3.0-or-later
component  : desktop
summary    : slop (Select Operation) is an application that queries for a selection
    from the user and prints the region to stdout
description: |
    slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
libsplit   : no
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(icu-uc)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
